Insert into crc_pilot.biospecimen (BIOSPECIMEN_ID,CLASS,NAME,PATIENT_ID,BIOSPECIMEN_PARENT_ID,PROTOCOL_ID,DISEASED,INSERT_USER,INSERT_DATE,INSERT_METHOD,ATTRIBUTE_TIMEPOINT_ID,AGE_AT_EVENT) values (crc_pilot.biospecimen_sequence.nextval,'SAMPLE','A584',(select patient_id from crc_pilot.patient where data_source_internal_id = 'A584'),null,null,0,'ACS224',to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'manual',0,null);
Insert into crc_pilot.biospecimen (BIOSPECIMEN_ID,CLASS,NAME,PATIENT_ID,BIOSPECIMEN_PARENT_ID,PROTOCOL_ID,DISEASED,INSERT_USER,INSERT_DATE,INSERT_METHOD,ATTRIBUTE_TIMEPOINT_ID,AGE_AT_EVENT) values (crc_pilot.biospecimen_sequence.nextval,'SAMPLE','A548',(select patient_id from crc_pilot.patient where data_source_internal_id = 'A548'),null,null,0,'ACS224',to_timestamp('16-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'manual',0,null);
Insert into crc_pilot.biospecimen (BIOSPECIMEN_ID,CLASS,NAME,PATIENT_ID,BIOSPECIMEN_PARENT_ID,PROTOCOL_ID,DISEASED,INSERT_USER,INSERT_DATE,INSERT_METHOD,ATTRIBUTE_TIMEPOINT_ID,AGE_AT_EVENT) values (crc_pilot.biospecimen_sequence.nextval,'SAMPLE','A632',(select patient_id from crc_pilot.patient where data_source_internal_id = 'A632'),null,null,0,'ACS224',to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'manual',0,null);
Insert into crc_pilot.biospecimen (BIOSPECIMEN_ID,CLASS,NAME,PATIENT_ID,BIOSPECIMEN_PARENT_ID,PROTOCOL_ID,DISEASED,INSERT_USER,INSERT_DATE,INSERT_METHOD,ATTRIBUTE_TIMEPOINT_ID,AGE_AT_EVENT) values (crc_pilot.biospecimen_sequence.nextval,'SAMPLE','A651',(select patient_id from crc_pilot.patient where data_source_internal_id = 'A651'),null,null,0,'ACS224',to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'manual',0,null);
Insert into crc_pilot.biospecimen (BIOSPECIMEN_ID,CLASS,NAME,PATIENT_ID,BIOSPECIMEN_PARENT_ID,PROTOCOL_ID,DISEASED,INSERT_USER,INSERT_DATE,INSERT_METHOD,ATTRIBUTE_TIMEPOINT_ID,AGE_AT_EVENT) values (crc_pilot.biospecimen_sequence.nextval,'SAMPLE','A734',(select patient_id from crc_pilot.patient where data_source_internal_id = 'A734'),null,null,0,'ACS224',to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'manual',0,null);
Insert into crc_pilot.biospecimen (BIOSPECIMEN_ID,CLASS,NAME,PATIENT_ID,BIOSPECIMEN_PARENT_ID,PROTOCOL_ID,DISEASED,INSERT_USER,INSERT_DATE,INSERT_METHOD,ATTRIBUTE_TIMEPOINT_ID,AGE_AT_EVENT) values (crc_pilot.biospecimen_sequence.nextval,'SAMPLE','B20',(select patient_id from crc_pilot.patient where data_source_internal_id = 'B20'),null,null,0,'ACS224',to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'manual',0,null);
Insert into crc_pilot.biospecimen (BIOSPECIMEN_ID,CLASS,NAME,PATIENT_ID,BIOSPECIMEN_PARENT_ID,PROTOCOL_ID,DISEASED,INSERT_USER,INSERT_DATE,INSERT_METHOD,ATTRIBUTE_TIMEPOINT_ID,AGE_AT_EVENT) values (crc_pilot.biospecimen_sequence.nextval,'SAMPLE','B155',(select patient_id from crc_pilot.patient where data_source_internal_id = 'B155'),null,null,0,'ACS224',to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'manual',0,null);
Insert into crc_pilot.biospecimen (BIOSPECIMEN_ID,CLASS,NAME,PATIENT_ID,BIOSPECIMEN_PARENT_ID,PROTOCOL_ID,DISEASED,INSERT_USER,INSERT_DATE,INSERT_METHOD,ATTRIBUTE_TIMEPOINT_ID,AGE_AT_EVENT) values (crc_pilot.biospecimen_sequence.nextval,'SAMPLE','B296',(select patient_id from crc_pilot.patient where data_source_internal_id = 'B296'),null,null,0,'ACS224',to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'manual',0,null);
Insert into crc_pilot.biospecimen (BIOSPECIMEN_ID,CLASS,NAME,PATIENT_ID,BIOSPECIMEN_PARENT_ID,PROTOCOL_ID,DISEASED,INSERT_USER,INSERT_DATE,INSERT_METHOD,ATTRIBUTE_TIMEPOINT_ID,AGE_AT_EVENT) values (crc_pilot.biospecimen_sequence.nextval,'SAMPLE','B309',(select patient_id from crc_pilot.patient where data_source_internal_id = 'B309'),null,null,0,'ACS224',to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'manual',0,null);
Insert into crc_pilot.biospecimen (BIOSPECIMEN_ID,CLASS,NAME,PATIENT_ID,BIOSPECIMEN_PARENT_ID,PROTOCOL_ID,DISEASED,INSERT_USER,INSERT_DATE,INSERT_METHOD,ATTRIBUTE_TIMEPOINT_ID,AGE_AT_EVENT) values (crc_pilot.biospecimen_sequence.nextval,'SAMPLE','B312',(select patient_id from crc_pilot.patient where data_source_internal_id = 'B312'),null,null,0,'ACS224',to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'manual',0,null);

REM INSERTING into REDUCTION_ANALYSIS
Insert into crc_pilot.REDUCTION_ANALYSIS (ID,VERSION,ALGORITHM,ALGORITHM_TYPE,BIOSPECIMEN_ID,DATE_CREATED,NAME,DESIGN_TYPE) values (crc_pilot.reduction_analysis_sequence.nextval,null,'FMR','reduction',(select biospecimen_id from crc_pilot.biospecimen where NAME = 'A584'),to_timestamp('16-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'patient_A584','COPY_NUMBER');
Insert into crc_pilot.REDUCTION_ANALYSIS (ID,VERSION,ALGORITHM,ALGORITHM_TYPE,BIOSPECIMEN_ID,DATE_CREATED,NAME,DESIGN_TYPE) values (crc_pilot.reduction_analysis_sequence.nextval,null,'FMR','reduction',(select biospecimen_id from crc_pilot.biospecimen where NAME = 'A548'),to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'patient_A548','COPY_NUMBER');
Insert into crc_pilot.REDUCTION_ANALYSIS (ID,VERSION,ALGORITHM,ALGORITHM_TYPE,BIOSPECIMEN_ID,DATE_CREATED,NAME,DESIGN_TYPE) values (crc_pilot.reduction_analysis_sequence.nextval,null,'FMR','reduction',(select biospecimen_id from crc_pilot.biospecimen where NAME = 'A632'),to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'patient_A632','COPY_NUMBER');
Insert into crc_pilot.REDUCTION_ANALYSIS (ID,VERSION,ALGORITHM,ALGORITHM_TYPE,BIOSPECIMEN_ID,DATE_CREATED,NAME,DESIGN_TYPE) values (crc_pilot.reduction_analysis_sequence.nextval,null,'FMR','reduction',(select biospecimen_id from crc_pilot.biospecimen where NAME = 'A651'),to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'patient_A651','COPY_NUMBER');
Insert into crc_pilot.REDUCTION_ANALYSIS (ID,VERSION,ALGORITHM,ALGORITHM_TYPE,BIOSPECIMEN_ID,DATE_CREATED,NAME,DESIGN_TYPE) values (crc_pilot.reduction_analysis_sequence.nextval,null,'FMR','reduction',(select biospecimen_id from crc_pilot.biospecimen where NAME = 'A734'),to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'patient_A734','COPY_NUMBER');
Insert into crc_pilot.REDUCTION_ANALYSIS (ID,VERSION,ALGORITHM,ALGORITHM_TYPE,BIOSPECIMEN_ID,DATE_CREATED,NAME,DESIGN_TYPE) values (crc_pilot.reduction_analysis_sequence.nextval,null,'FMR','reduction',(select biospecimen_id from crc_pilot.biospecimen where NAME = 'B20'),to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'patient_B20','COPY_NUMBER');
Insert into crc_pilot.REDUCTION_ANALYSIS (ID,VERSION,ALGORITHM,ALGORITHM_TYPE,BIOSPECIMEN_ID,DATE_CREATED,NAME,DESIGN_TYPE) values (crc_pilot.reduction_analysis_sequence.nextval,null,'FMR','reduction',(select biospecimen_id from crc_pilot.biospecimen where NAME = 'B155'),to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'patient_B155','COPY_NUMBER');
Insert into crc_pilot.REDUCTION_ANALYSIS (ID,VERSION,ALGORITHM,ALGORITHM_TYPE,BIOSPECIMEN_ID,DATE_CREATED,NAME,DESIGN_TYPE) values (crc_pilot.reduction_analysis_sequence.nextval,null,'FMR','reduction',(select biospecimen_id from crc_pilot.biospecimen where NAME = 'B296'),to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'patient_B296','COPY_NUMBER');
Insert into crc_pilot.REDUCTION_ANALYSIS (ID,VERSION,ALGORITHM,ALGORITHM_TYPE,BIOSPECIMEN_ID,DATE_CREATED,NAME,DESIGN_TYPE) values (crc_pilot.reduction_analysis_sequence.nextval,null,'FMR','reduction',(select biospecimen_id from crc_pilot.biospecimen where NAME = 'B309'),to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'patient_B309','COPY_NUMBER');
Insert into crc_pilot.REDUCTION_ANALYSIS (ID,VERSION,ALGORITHM,ALGORITHM_TYPE,BIOSPECIMEN_ID,DATE_CREATED,NAME,DESIGN_TYPE) values (crc_pilot.reduction_analysis_sequence.nextval,null,'FMR','reduction',(select biospecimen_id from crc_pilot.biospecimen where NAME = 'B312'),to_timestamp('19-APR-10','DD-MON-RR HH.MI.SSXFF AM'),'patient_B312','COPY_NUMBER');

insert into common.data_source_content (data_source_content_id, data_source_id, content_type, show_in_gui) values (common.dsc_sequence.nextval, (select data_source_id from common.data_source where short_name = 'CRC_PILOT'), 'COPY_NUMBER', 1);