-- create molecule
CREATE TABLE DRUG.MOLECULE
(
  ID NUMBER NOT NULL,
  ACCEPTOR_ATOMS NUMBER(19, 0),
  CHIRAL NUMBER(19, 0),
  CLOGP FLOAT(126),
  DATE_CREATED DATE,
  DONOR_ATOMS NUMBER(19, 0),
  FORMULA VARCHAR2(255 BYTE),
  LAST_UPDATED DATE,
  NAME VARCHAR2(255 BYTE),
  ROTATABLE_BONDS NUMBER(19, 0),
  CHEMICAL_NAME VARCHAR2(255 BYTE),
  WEIGHT NUMBER,
  VERSION NUMBER,
  REFRACTIVITY FLOAT(126),
  PH NUMBER,
  SOLUBILITY VARCHAR2(20 BYTE)
, CONSTRAINT MOLECULE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
  TABLESPACE "DRUG_TS"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 80K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
;

-- create molecule target.
CREATE TABLE DRUG.MOLECULE_TARGET
(
  ID NUMBER(19, 0) NOT NULL,
  VERSION NUMBER(19, 0),
  BINDING_DATA VARCHAR2(255 BYTE),
  DATE_CREATED DATE,
  LAST_UPDATED DATE,
  MOLECULE_ID NUMBER(19, 0) NOT NULL,
  PROTEIN_ID NUMBER(19, 0) NOT NULL
, CONSTRAINT MOLECULE_TARGET_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
  TABLESPACE "DRUG_TS"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 80K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
;

-- create structure
CREATE TABLE DRUG.STRUCTURE
(
  ID NUMBER(19, 0) NOT NULL,
  VERSION NUMBER(19, 0),
  DATE_CREATED DATE,
  LAST_UPDATED DATE,
  MOLECULE_ID NUMBER(19, 0),
  MOLECULE_TARGET_ID NUMBER(19, 0),
  STRUCTURE_FILE_ID NUMBER(19, 0) NOT NULL,
  PROTEIN_ID NUMBER(19, 0),
  STRUCTURE_DB VARCHAR2(20 BYTE)
, CONSTRAINT STRUCTURE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
  TABLESPACE "DRUG_TS"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 80K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
;

ALTER TABLE DRUG.STRUCTURE
ADD CONSTRAINT STRUCTURE_MOLECULE_FK FOREIGN KEY
(
  MOLECULE_ID
)
REFERENCES DRUG.MOLECULE
(
ID
) ENABLE
;

ALTER TABLE DRUG.STRUCTURE
ADD CONSTRAINT STRUCTURE_PROTEIN_FK FOREIGN KEY
(
  PROTEIN_ID
)
REFERENCES COMMON.PROTEIN
(
ID
) ENABLE
;

ALTER TABLE DRUG.STRUCTURE
ADD CONSTRAINT STRUCTURE_MOLECULETARGET_FK FOREIGN KEY
(
  MOLECULE_TARGET_ID
)
REFERENCES DRUG.MOLECULE_TARGET
(
ID
) ENABLE
;

ALTER TABLE DRUG.STRUCTURE
ADD CONSTRAINT STRUCTURE_STRUCTURE_FILE_FK FOREIGN KEY
(
  STRUCTURE_FILE_ID
)
REFERENCES DRUG.STRUCTURE_FILE
(
ID
) ENABLE
;

-- create structure_file
CREATE TABLE DRUG.STRUCTURE_FILE
(
  ID NUMBER(19, 0) NOT NULL,
  VERSION NUMBER(19, 0),
  DATE_CREATED DATE,
  FILE_FORMAT_ID NUMBER(19, 0),
  FILE_SIZE NUMBER(19, 0),
  FILE_TYPE_ID NUMBER(19, 0),
  LAST_UPDATED DATE,
  NAME VARCHAR2(255 BYTE) NOT NULL,
  RELATIVE_PATH VARCHAR2(255 BYTE) NOT NULL
, CONSTRAINT STRUCTURE_FILE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
  TABLESPACE "DRUG_TS"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 80K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
;

ALTER TABLE DRUG.STRUCTURE_FILE
ADD CONSTRAINT STRUCTURE_FILE_FORMAT_FK FOREIGN KEY
(
  FILE_FORMAT_ID
)
REFERENCES COMMON.FILE_FORMAT
(
FILE_FORMAT_ID
) ENABLE
;

